### ISSUE TITLE
Unrar

### ISSUE THREAD

**Issue by danpowell88** [justmiles/docker-qbittorrent#1]
How would I go about getting unrar installed with this.

I tried adding the following  variable but its not installed.
`BUILD_PACKAGES :git python libboost-dev libboost-system-dev build-essential libqt4-dev qtbase5-dev qttools5-dev-tools libboost-system-dev libboost-chrono-dev libboost-random-dev libssl-dev libgeoip-dev pkg-config automake libtool unrar-free`
If I log on locally and run it is installed successfully
```
apt-get update
apt-get install unrar-free
```

Cheers

**Comment by justmiles** [comment]
Build packages only exist during the build. They're later purged during cleanup (line 33). If you want a package to persist, add it to the install command next to `geoip-database`.
